version: '3'

services:
   jenkins:
     image: jenkins
     
      
     ports:
       - "8000:8080"
     restart: always
     
   db:
     image: mysql:5.7
   adminer:
     image: adminer
     restart: always
     ports:
      - "8090:8080" 
     environment:
        - MYSQL_ROOT_PASSWORD=petclinic
        - MYSQL_DATABASE=petclinic
    
    

